version: "2"
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - godox
    - mnd
    - varnamelen
    - noinlineerr
    - lll
    - wsl
    - misspell
  settings:
    tagliatelle:
      case:
        rules:
          json: snake
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
